MODEL_NAME = "openai/gpt-oss-120b"
TEMPERATURE = 0
MAX_TOOL_ITERATIONS = 5
WORKSPACE_DIR = "workspace"
NOTES_FILE = "notes.txt"

MAX_CONTEXT_TOKENS = 100000
MAX_REQUEST_TOKENS = 4500
SUMMARY_TRIGGER_TOKENS = 6000

CONTEXT_CHECK_MESSAGES = 40

CONVERSATION_HISTORY_LIMIT = 50


