MODEL_NAME = "openai/gpt-oss-120b"
TEMPERATURE = 0
MAX_TOOL_ITERATIONS = 5
WORKSPACE_DIR = "workspace"
NOTES_FILE = "notes.txt"

MAX_CONTEXT_TOKENS = 100000

CONTEXT_CHECK_MESSAGES = 40

CONVERSATION_HISTORY_LIMIT = 50